---
- hosts: all
  vars:
    project_build_url: http://hg.rbc.ru/repo/rbc.ru/fp/6.0/build_backend
    project_host: v6.bo.rbc.vagrant
    project_path: /vagrant/
    user:
      full_name: Sample User
      name: user
      email: user@example.com
      password: "****"
  roles:
    - common
  tasks:
    - name: update apt cache
      sudo: yes
      apt: update_cache=yes
    - name: install dependencies
      apt: name={{ item }} state=latest
      sudo: true
      with_items:
        - php5-cli # required for haru
        - git # required for haru
        - mercurial # required for haru
        - enchant # for spell-check
        - aspell-ru # for spell-check
        - python-virtualenv
        - python-dev
        - unzip
        - libgd2-xpm-dev
        - libmemcached-dev
        - daemontools
        - libxml2-dev
        - libxslt1-dev
    - name: checkout haru
      git: repo=https://github.com/TheRatG/haru.git
         dest=/vagrant/haru
    - name: setup .hgrc
      template:
        src=templates/.hgrc.j2
        dest=/home/vagrant/.hgrc
    - name: get build
      shell: yes no | /vagrant/haru/phing get-build -Dpath={{ project_path }} -Dhost={{ project_host }} -Dvcs=hg -Dsrc={{ project_build_url }}
      args:
        chdir: /vagrant/haru
        creates: /vagrant/build

#  handlers:
#    - name: restart ntpd
#      service: name=ntpd state=restarted

