---
- hosts: all
  pre_tasks:
    - name: update apt cache
      sudo: yes
      apt: update_cache=yes
  roles:
    - common
    - haru
  tasks:
    - name: install project dependencies
      apt: name={{ item }} state=present
      sudo: true
      with_items:
        - enchant # for spell-check
        - aspell-ru # for spell-check
        - python-virtualenv
        - python-dev
        - unzip
        - libgd2-xpm-dev
        - libmemcached-dev
        - daemontools
        - libxml2-dev
        - libxslt1-dev
